"""create subscriber table

Revision ID: 512fac784743
Revises: a03b1b0888f4
Create Date: 2021-09-25 23:23:47.310931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '512fac784743'
down_revision = 'a03b1b0888f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_name', sa.String(length=50), nullable=True),
    sa.Column('subscriber_email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscriber_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscribers')
    # ### end Alembic commands ###
